### ISSUE TITLE
NFS data set

### ISSUE THREAD

**Issue by Clarkwk** [Little-Podi/AiATrack#18]
Hello, it is a great honor to see your excellent work! I would like to ask you if you have any questions about the NFS data set downloaded from the NFS Data set official website and how to set the path of the NFS data set.

There are no anno and sequences files in the original dataset, and I got the following ValueError when I ran it: could not convert string '0 520 260 564 369 1 0 0 1 "person"' to float64 at row 0, column 1.

I wonder if you have met it before. Looking forward to your reply, thank you

**Comment by Little-Podi** [comment]
Hi there, may I ask if you are downloading NfS directly from [here](http://ci2cv.net/nfs/index.html)? That's exactly what I did and the code would run smoothly if I remember it correctly. Maybe these two answers (https://github.com/visionml/pytracking/issues/211, https://github.com/visionml/pytracking/issues/377) can help you to solve your issue. If it doesn't work, I also found a newly opened issue (https://github.com/visionml/pytracking/issues/400) that mentions a similar question. Since the codebase is based on [PyTracking](https://github.com/visionml/pytracking), I think most instructions and solutions from them are probably suit for this project as well.
