### ISSUE TITLE
epoch numbers

### ISSUE THREAD

**Issue by ElliottZhen** [Little-Podi/AiATrack#19]
Hi, excuse me, is the main reason the training rounds are 500 because of the learnable target background embedding?I found out got10k also trained 500 epochs.Sorry to bother you. Thank you.

**Comment by ElliottZhen** [comment]
I want to include the target background embedding you proposed in my model, so I would like to ask this question, because my training amount may not reach 500* 60,000

**Comment by Little-Podi** [comment]
We chose the round of training as 500 simply following [DETR](https://arxiv.org/abs/2005.12872). The main reason for such a long training period is that all of the attention layers for feature aggregation are newly initialized. Without any pretrained weights loaded, the global attention operation may take a long time to converge from scratch. The embedding itself doesn't effect much.

**Comment by Little-Podi** [comment]
Since our tracking model contains much less Transformer layers compared with the original DETR, I think you can cut the training budget to 300 or 200 epochs. From my own experience, it won't degrade the tracking performance too much so you can get some quick feedbacks in the earlier explorations. Less epochs are also possible as it mainly depends on your model complexity and more improtantly, the pretraining weights for initialization. For this project, remember to set `LR_DROP_EPOCH` in your config files accordingly to ensure a smooth convergence.

**Comment by ElliottZhen** [comment]
Thank you very much！I will try it.
