### ISSUE TITLE
单张2080ti训练时间

### ISSUE THREAD

**Issue by KristianZZ** [Little-Podi/AiATrack#20]
你好，用2080ti在单个got10k数据集上训练，12个小时只训练了5轮正常吗？

**Comment by Little-Podi** [comment]
I think it's somewhat slow. Please make sure your CPU is not fully occupied and your data is stored on SSD. There's no big difference in efficiency between only training on GOT-10k and joint training on all since the num of samples is fixed for each epoch (due to the sampling strategy for multiple datasets). BTW, from my experience, training only with GOT-10k is a little slower (probably caused by data processing).

**Comment by KristianZZ** [comment]
好的，非常感谢!
