### ISSUE TITLE
关于在LASOT上的raw result.

### ISSUE THREAD

**Issue by RelayZ** [Little-Podi/AiATrack#3]
作者您好，请问在LASOT数据集上的raw results是否可以公开？

**Comment by Little-Podi** [comment]
Hi, you can find the raw results on all benchmarks included in the paper via [this link](https://github.com/Little-Podi/AiATrack/releases/download/downloads/Raw_Results.zip). If there is any trouble, please let me know.

**Comment by RelayZ** [comment]
里面似乎只有GOT-10K、TrackingNet、OTB的结果。您是否可以重新上传完整的LASOT的raw results，感谢！

**Comment by Little-Podi** [comment]
Sorry for troubling you. In order to facilitate the evaluation, I didn't divide the results of each benchmark into different folders. Except the datasets you mentioned (prefix 'nfs_' denotes the results on NFS, 'otb_' denotes the results on OTB, and 'uav_' denotes the results on UAV), **the remaining 430 TXT files** (such as airplane-1.txt, atv-1.txt) are the results on LaSOT, including its testing subset (totaling 280 sequences) and its extension subset (totaling 150 sequences).

**Comment by RelayZ** [comment]
Thank you very much for your reply, the problem has been solved.
