### ISSUE TITLE
DEMO 

### ISSUE THREAD

**Issue by MUHAMMEDZEYN** [Little-Podi/AiATrack#5]
It would be so useful if we can test the tracker with our own video. Can you please share the demo script if existed ?

**Comment by Little-Podi** [comment]
Thanks for your advice. Currently, I'm not available to extend and test this function. However, you can refer to pytracking/run_video.py in [PyTracking](https://github.com/visionml/pytracking) or tracking/video_demo.py in [STARK](https://github.com/researchmm/Stark). I think it can be smoothly integrated since the organization of our project is similar to their code.

**Comment by MUHAMMEDZEYN** [comment]
Thanks for your reply. Actually I worked on pytracking recently I will try your suggestion if I can make it work I will share the results.

**Comment by reza-shahriari** [comment]
@MUHAMMEDZEYN I want demo my video with aiatrack as you said. have you found a way ?
