### ISSUE TITLE
Stuck in "loading extension module _prroi_pooling"

### ISSUE THREAD

**Issue by faicaiwawa** [Little-Podi/AiATrack#8]
Thank you for your excellent work, it really do teach me a lot . but i meet a problem when i training aiatrack-got on two rtx 2080ti，it stuck in  "loading extension module _prroi_pooling" and no more forward ，i have ever trained other project which also have prpooling , but  i dont't meet this problem . so i want to know how to Adjust the training parameters？

**Comment by Little-Podi** [comment]
Can you run aiatrack smoothly instead of aiatrack-got? If so, I think you don't need to adjust the configs. A very quick but brute solution to try is restarting your CPU cache or directly rebooting your server if you are allowed to have root access. If you meet trouble in both aiatrack and aiatrack-got, I will recommend to change the verison of your environment, especially using `pytorch <= 1.10.1`. Wish you good luck!

**Comment by Little-Podi** [comment]
Also, cloning the original [PreciseRoIPooling](https://github.com/vacancy/PreciseRoIPooling) repo and recompiling it are worth trying. Sorry for my somewhat blind suggestions, but I haven't used this external for a long time.

**Comment by faicaiwawa** [comment]
> Also, cloning the original [PreciseRoIPooling](https://github.com/vacancy/PreciseRoIPooling) repo and recompiling it are worth trying. Sorry for my somewhat blind suggestions, but I haven't used this external for a long time.

thank you ! i can run aiatrack smoothly， I also asked other people who trained aiatrack,  they told me that they also met same problem, and they think training  is actually running, but Just no visual progress bar, haha, thanks for your reply!
